{{- if .Values.operator.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstorcontrollers.linstor.wedos.org
spec:
  group: linstor.wedos.org
  names:
    kind: LinstorController
    listKind: LinstorControllerList
    plural: linstorcontrollers
    singular: linstorcontroller
  scope: Cluster
  subresources:
    status: {}
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        metadata:
          type: object
          properties:
            name:
              type: string
              enum: [ controller ]
        spec:
          type: object
          required:
          - properties
          properties:
            properties:
              type: array
              items:
                type: object
                required:
                - name
                - value
                properties:
                  name:
                    type: string
                  value:
                    type: string
                    pattern: '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstornodes.linstor.wedos.org
spec:
  group: linstor.wedos.org
  names:
    kind: LinstorNode
    listKind: LinstorNodeList
    plural: linstornodes
    singular: linstornode
  scope: Cluster
  subresources:
    status: {}
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
          - netInterfaces
          properties:
            type:
              type: string
              enum: [ Controller, Auxiliary, Combined, Satellite ]
            netInterfaces:
              type: array
              required:
              items:
                type: object
                required:
                - name
                - address
                properties:
                  name:
                    type: string
                  address:
                    type: string
                    pattern: '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
            properties:
              type: array
              items:
                type: object
                required:
                - name
                - value
                properties:
                  name:
                    type: string
                  value:
                    type: string
  additionalPrinterColumns:
  - name: Status
    type: string
    description: Status
    JSONPath: .status.status
  - name: Addresses
    type: string
    description: Addresse
    JSONPath: .spec.netInterfaces[*].address
    priority: 0
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstorstoragepools.linstor.wedos.org
spec:
  group: linstor.wedos.org
  names:
    kind: LinstorStoragePool
    listKind: LinstorStoragePoolList
    plural: linstorstoragepools
    singular: linstorstoragepool
  scope: Cluster
  subresources:
    status: {}
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        metadata:
          type: object
          properties:
            name:
              type: string
              pattern: '^([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])\.(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
        spec:
          type: object
          required:
          - driver
          properties:
            driver:
              type: string
              enum: [ DISKLESS, LVM, LVM_THIN, ZFS, ZFS_THIN, SWORDFISH_INITIATOR, SWORDFISH_TARGET ]
            properties:
              type: array
              items:
                type: object
                required:
                - name
                - value
                properties:
                  name:
                    type: string
                  value:
                    type: string
  additionalPrinterColumns:
  - name: Status
    type: string
    description: Status
    JSONPath: .status.status
  - name: Driver
    type: string
    description: Driver
    JSONPath: .spec.driver
    priority: 0
  - name: PoolName
    type: string
    description: PoolName
    JSONPath: .status.poolName
    priority: 0
  - name: Free
    type: string
    description: FreeCapacity
    JSONPath: .status.freeCapacity
    priority: 0
  - name: Total
    type: string
    description: TotalCapacity
    JSONPath: .status.totalCapacity
    priority: 0
  - name: Snapshots
    type: string
    description: SupportsSnapshots
    JSONPath: .status.supportsSnapshots
    priority: 0
{{- end }}
