{{- $fullName := include "linstor.fullname" . -}}
{{- if .Values.controller.ssl.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-stunnel
  namespace: {{ .Release.Namespace }}
data:
  stunnel-client.conf: |+
    foreground = yes
    delay = yes
    debug = 4
    [PSK client 1]
    client = yes
    accept = 127.0.0.1:3370
    connect = {{ $fullName }}-controller:{{ .Values.controller.ssl.port }}
    cert = /tls/tls.crt
    key = /tls/tls.key
    CAfile = /tls/ca.crt
{{- end }}
