---
- set_fact:
    metadata: "{{ res.metadata }}"
    api_version: "{{ res.apiVersion }}"
    kind: "{{ res.kind }}"
    status: "{{ res.status | default({}) }}"
    configure: "{{ configure | default(false) }}"
  vars:
    res: "{{ vars.values() | selectattr('apiVersion', 'defined') | first }}"

- set_fact:
    default_interface:
      name: default
      address: '{{ (net_interfaces | selectattr("name", "equalto", "default") | first).address }}'

- name: 'linstor node list'
  uri:
    url: 'http://{{ linstor_controller }}/v1/nodes'
  register: node_list

- set_fact:
    node_info: "{{ node_list.json | selectattr('name', 'match', '(?i)^' + meta.name + '$') | first | default({})}}"

- name: 'linstor node create'
  uri:
    url: 'http://{{ linstor_controller }}/v1/nodes'
    method: POST
    body_format: json
    status_code: 201
    body: '{"net_interfaces": [{"satellite_port": {{ satellite_port }}, "satellite_encryption_type": "{{ satellite_encryption_type }}", "name": "default", "address": "{{ default_interface.address }}"}], "type": "{{ type }}", "name": "{{ meta.name }}"}'
  when: "node_info.name is not defined"
  changed_when: true

- name: 'linstor node interface create'
  uri:
    url: 'http://{{ linstor_controller }}/v1/nodes/{{ meta.name }}/net-interfaces'
    method: POST
    body_format: json
    status_code: 201
    body: '{"name": "{{ item.name }}", "address": "{{ item.address }}"}'
  when: "item.name != 'default' and filtered_interfaces | length == 0"
  changed_when: true
  vars:
    filtered_interfaces: '{{ node_info.net_interfaces | default([default_interface]) | selectattr("name", "equalto", item.name) | list }}'
  loop: '{{ net_interfaces }}'

- name: 'linstor node interface modify address'
  uri:
    url: 'http://{{ linstor_controller }}/v1/nodes/{{ meta.name }}/net-interfaces/{{ item.name }}'
    method: PUT
    body_format: json
    status_code: 200
    body: '{"name": "{{ item.name }}", "address": "{{ item.address }}"}'
  when: "filtered_interfaces | length != 0 and filtered_interfaces[0].address != item.address"
  changed_when: true
  vars:
    filtered_interfaces: '{{ node_info.net_interfaces | default([default_interface]) | selectattr("name", "equalto", item.name) | list }}'
  loop: '{{ net_interfaces }}'

- name: 'linstor node set-properties'
  uri:
    url: 'http://{{ linstor_controller }}/v1/nodes/{{ meta.name }}'
    method: PUT
    body_format: json
    status_code: 200
    body: '{"override_props": {"{{ item.name }}": "{{ item.value }}"}}'
  when: 'node_info.props is not defined or node_info.props[item.name] is not defined or node_info.props[item.name] != item.value'
  changed_when: true
  loop: '{{ properties }}'

- name: "update status"
  k8s_status:
    api_version: '{{ api_version }}'
    kind: '{{ kind }}'
    name: '{{ meta.name }}'
    status:
      status: '{{ node_info.connection_status }}'
