apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: linstor-controller
  name: linstor-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linstor-controller
  serviceName: linstor-controller
  template:
    metadata:
      labels:
        app: linstor-controller
    spec:
      containers:
      - command:
        - /tini
        - --
        - /usr/share/linstor-server/bin/Controller
        - --logs=/logs
        - --config-directory=/config
        - --rest-bind=127.0.0.1:3370
        image: kvaps/linstor-controller:v0.9.13
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - timeout
            - "5"
            - linstor
            - controller
            - list-properties
          initialDelaySeconds: 60
          periodSeconds: 10
        name: linstor-controller
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /logs
          name: logs
      - args:
        - /etc/stunnel/stunnel-server.conf
        image: kvaps/linstor-stunnel:v0.9.13
        imagePullPolicy: Always
        name: stunnel
        ports:
        - containerPort: 3371
          name: restapi
        volumeMounts:
        - mountPath: /etc/stunnel
          name: stunnel-config
      imagePullSecrets:
      - name: regsecret
      initContainers:
      - command:
        - /bin/bash
        - -c
        - |-
          echo "setcfgval namespace(netcom) key(PlainConnector/bindaddress) value(127.0.0.1)
          setSecLvl secLvl(NO_SECURITY)
          shutdown" | /usr/share/linstor-server/bin/Controller -d --logs=/logs --config-directory=/config --rest-bind=127.0.0.1:3370
        image: kvaps/linstor-controller:v0.9.13
        imagePullPolicy: Always
        name: init
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /logs
          name: logs
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: config
        secret:
          secretName: linstor-controller
      - name: stunnel-config
        projected:
          sources:
          - configMap:
              name: linstor-stunnel
          - secret:
              name: linstor-stunnel
      - hostPath:
          path: /var/log/linstor-controller
        name: logs
---
apiVersion: v1
kind: Service
metadata:
  name: linstor-controller
spec:
  ports:
  - name: restapi
    port: 3371
    targetPort: 3371
  selector:
    app: linstor-controller
