---
- set_fact:
    metadata: "{{ res.metadata }}"
    api_version: "{{ res.apiVersion }}"
    kind: "{{ res.kind }}"
    status: "{{ res.status | default({}) }}"
    storage_pool_name: "{{ meta.name.split('.')[0] }}"
    node_name: "{{ meta.name.split('.')[1:] | join('.') }}"
  vars:
    res: "{{ vars.values() | selectattr('apiVersion', 'defined') | first }}"

- name: 'linstor storage-pool list'
  uri:
    url: 'http://{{ linstor_controller }}/v1/view/storage-pools?nodes={{ node_name }}&storage_pools={{ storage_pool_name }}'
  register: storage_pool_list

- set_fact:
    initial_config: |
      storage_pool_name: "{{ storage_pool_name }}"
      provider_kind: "{{ driver }}"
      props: {
        {% if driver == 'LVM' %}
        StorDriver/LvmVg: '{{ (properties | selectattr("name", "equalto", "StorDriver/LvmVg") | first).value }}'
        {% elif driver == 'LVM_THIN' %}
        StorDriver/ThinPool: '{{ (properties | selectattr("name", "equalto", "StorDriver/ThinPool") | first).value }}'
        StorDriver/LvmVg: '{{ (properties | selectattr("name", "equalto", "StorDriver/LvmVg") | first).value }}'
        {% elif driver == 'ZFS' %}
        StorDriver/ZPool: '{{ (properties | selectattr("name", "equalto", "StorDriver/ZPool") | first).value }}'
        {% elif driver == 'ZFS_THIN' %}
        StorDriver/ZPoolThin: '{{ (properties | selectattr("name", "equalto", "StorDriver/ZPoolThin") | first).value }}'
        {% elif driver == 'SWORDFISH_TARGET' %}
        StorDriver/SwordfishStorPool: '{{ (properties | selectattr("name", "equalto", "StorDriver/SwordfishStorPool") | first).value }}'
        {% endif %}
        }
    status_entries: |
      {% if storage_pool_list.json | length != 0 %}
      status: '{% if storage_pool_list.json[0].reports is defined %}Warning{% else %}OK{% endif %}'
      {% if storage_pool_list.json[0].free_capacity is defined and storage_pool_list.json[0].free_capacity != 9223372036854775807 %}
      freeCapacity: '{{ storage_pool_list.json[0].free_capacity }}'
      {% endif %}
      {% if storage_pool_list.json[0].total_capacity is defined and storage_pool_list.json[0].total_capacity != 9223372036854775807 %}
      totalCapacity: '{{ storage_pool_list.json[0].total_capacity }}'
      {% endif %}
      {% if storage_pool_list.json[0].static_traits is defined and storage_pool_list.json[0].static_traits.SupportsSnapshots is defined %}
      supportsSnapshots: '{{ storage_pool_list.json[0].static_traits.SupportsSnapshots }}'
      {% endif %}
      {% endif %}
      {% if pool_name != '' %}
      pool_name: '{{ pool_name | trim }}'
      {% endif %}
  vars:
    pool_name: |
      {% if driver == 'LVM' %}{{
        (properties | selectattr('name', 'equalto', 'StorDriver/LvmVg') | first).value
      }}{% elif driver == 'LVM_THIN' %}{{
        (properties | selectattr('name', 'equalto', 'StorDriver/LvmVg') | first).value
        }}/{{
        (properties | selectattr('name', 'equalto', 'StorDriver/ThinPool') | first).value 
      }}{% elif driver == 'ZFS' %}{{
        (properties | selectattr('name', 'equalto', 'StorDriver/ZPool') | first).value
      }}{% elif driver == 'ZFS_THIN' %}{{
        (properties | selectattr('name', 'equalto', 'StorDriver/ZPoolThin') | first).value
      }}{% elif driver == 'SWORDFISH_TARGET' %}{{
        (properties | selectattr('name', 'equalto', 'StorDriver/SwordfishStorPool') | first).value
      }}{% endif %}

- name: "update status"
  k8s_status:
    api_version: '{{ api_version }}'
    kind: '{{ kind }}'
    name: '{{ meta.name }}'
    status: '{{ status_entries | from_yaml }}'

- block:
  - name: 'linstor storage-pool create'
    uri:
      url: 'http://{{ linstor_controller }}/v1/nodes/{{ node_name }}/storage-pools'
      method: POST
      body_format: json
      status_code: 201
      body: "{{ initial_config | from_yaml }}"
    when: "storage_pool_list.json | length == 0"
    changed_when: true
  rescue:
  - name: "update status"
    k8s_status:
      api_version: '{{ api_version }}'
      kind: '{{ kind }}'
      name: '{{ meta.name }}'
      status:
        status: ERROR
  - meta: end_play

- name: 'linstor storage-pool set-properties'
  uri:
    url: 'http://{{ linstor_controller }}/v1/nodes/{{ node_name }}/storage-pools/{{ storage_pool_name }}'
    method: PUT
    body_format: json
    status_code: 200
    body: '{"override_props": {"{{ item.name }}": "{{ item.value }}"}}'
  when: "(storage_pool_list.json | length == 0 is not defined and item.value not in initial_properties) or
         (storage_pool_list.json | length != 0 and (storage_pool_list.json[0].props[item.name] is not defined or storage_pool_list.json[0].props[item.name] != item.value))"
  changed_when: true
  loop: '{{ properties }}'
  vars:
    initial_properties:
    - 'StorDriver/LvmVg'
    - 'StorDriver/ThinPool'
    - 'StorDriver/ZPool'
    - 'StorDriver/ZPoolThin'
    - 'StorDriver/SwordfishStorPool'
